### ISSUE TITLE
拖动异常问题 pc端拖动N个组件，然后切换到手机端，进行向上的拖动，切回电脑端之后，组件宽度会变成50%

### ISSUE THREAD

**Issue by toxufe** [Liberty-liu/Everright-formEditor#14]
![GIF 2023-6-29 16-38-15](https://github.com/Liberty-liu/Everright-formEditor/assets/7663543/f8885aa3-5329-4d08-b2cd-060400d2c727)
pc端拖动N个组件，然后切换到手机端，进行向上的拖动，切回电脑端之后，组件宽度会变成50%

**Comment by Liberty-liu** [comment]
看到这里使用的模式：`layoutType1: Fields and layout not separated`.

这里内部的逻辑是当一个字段占据一行的时候会在其父级自动包裹一个inline容器，如下图所示
```mermaid
flowchart TB
    subgraph inline
    input
    end
```
```mermaid
flowchart TB
    subgraph inline
    textarea
    end
```
```mermaid
flowchart TB
    subgraph inline
    radio
    end
```
inline容器最多允许4个字段。
在pc拖拽是允许上下左右四个方向进行拖拽，在`layoutType1`模式mobile，只允许上下，禁用了左右模式。
当在mobile进行拖拽一个字段的时候，会自动将拖拽元素放入临近的inline中，会触发inline平均分配宽度的机制。

```mermaid
flowchart TB
    radio-->textarea
    subgraph inline
    textarea
    end
```
由于这里缺少一个能够体现层级的界面，所以会造成是一种bug的感觉，关于层级的界面原计划是在拖拽发生的时候，会将左侧字段面板展示层级界面，能够清晰的让使用者知道当前拖拽的字段会被放入到哪个层级

**Comment by toxufe** [comment]
好的  我明白了，非常感谢您认真且详细的回复，我是一个后端，对前端实在是不太擅长，谢谢了。
