### ISSUE TITLE
请教类似option字段，如何处理需要在后台获取的待选项

### ISSUE THREAD

**Issue by shang-zhen** [Liberty-liu/Everright-formEditor#16]
比如像您的另一个插件 Everright-filter 可以通过conditions接口获取到option 、select待选内容
这个插件可以添加2个特殊字段吗
比如： `type` = ‘server’，`condition-name`：`dept`
这样前端获取到json数据后可以发送到后台处理后，生成这种特殊字段的待选内容。

**Comment by Liberty-liu** [comment]
可以举一个详细点的例子吗

**Comment by shang-zhen** [comment]
就是关联其他字段
比如数据表： `client ` 中有字段为 `dept` 的下拉选项， 下拉选项的内容为后台client_dept表中获取
在您的这个插件中只能指定下拉选项的内容。
我的想法是 可以通过对 form表单中的`dept`字段，设置2个特殊的值，然后把form表单生成的json发送到后台，
后台过滤数据检测到这2个特殊的值就可以修改json内容，修改`dept`的下拉内容为`client_dept`数据表中的。。
表单能力有限😳，不知道我表述清楚了没😄

**Comment by Liberty-liu** [comment]
我可以这样理解吗？
希望如select的数据通过接口获取，对于每个可以配置数据的字段也都提供一种可以自定义URL和get params的功能

**Comment by shang-zhen** [comment]
> 我可以这样理解吗？
> 希望如select的数据通过接口获取，对于每个可以配置数据的字段也都提供一种可以自定义URL和get params的功能

嗯～这样就灵活多了。
