### ISSUE TITLE
【建议优化】selectElement.jsx

### ISSUE THREAD

**Issue by leefinder** [Liberty-liu/Everright-formEditor#19]
感谢，这个开源仓库给了我很多启发和帮助，在学习与应用的同时发现了一些小问题，以及自己的一些思考
代码片段：packages\formEditor\components\Selection\selectElement.jsx
> 230行，不建议直接重写document的事件(发现如果重写导致通过箭头调整宽度后，组件会拖不动)，所以调整了一下

![image](https://github.com/Liberty-liu/Everright-formEditor/assets/26495819/50237324-3185-4b9c-b349-bd2530d06669)

> 288行，这个拖拽handle区域，操作起来不是方便，可以调整直接在组件上拖动，相对比较灵活点

![image](https://github.com/Liberty-liu/Everright-formEditor/assets/26495819/a1fa9afd-db7a-4b3f-95d4-6b0b952da225)

> 336行，mask全局开启，可以通过判断props.data.type，给每一个组件都添加一个type，类似 `enter`，`box`，容器组件穿透，输入组件就默认打遮罩

```
 const maskNode = (
      <div class={[ns.e('mask')]} style={{ 'pointer-events': props?.data?.type !== 'enter' ? 'none' : 'all' }}>
      </div>
    )
```

> 效果

![GIF 2023-8-7 14-42-56](https://github.com/Liberty-liu/Everright-formEditor/assets/26495819/198214c7-0a61-4257-8324-9b8cec59a09c)

**Comment by Liberty-liu** [comment]
感谢认可，欢迎提pr，一块改进
