### ISSUE TITLE
能否提供页面切换-方便用这个做原型

### ISSUE THREAD

**Issue by lucktoo** [Liberty-liu/Everright-formEditor#8]
能否提供假数据的功能

**Comment by Liberty-liu** [comment]
@lucktoo 可以详细描述一下吗

**Comment by lucktoo** [comment]
你好，我是一名产品经理，业务主要是B端这块。想跟业务部门快速出原型，让业务部门能更直观知道系统是怎么设计的。

**Comment by Liberty-liu** [comment]
1. 关于数据方面现在有录入数据的方式(缺点是没有提供数据导入或者以代码的形式导入数据)。
2. 产研配合加快团队开发效率其实不该依赖一个开源的来玩，团队风格各不一样，最好拉着你们开发小伙伴一块开发一套适合你们的东西

**Comment by lucktoo** [comment]
那看来没戏了~~·目前b端 用figma画 效率还是不高。所以希望有一个快速的原型工具，而ax太落后了
